# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#212337"

# Main text color
theme[main_fg]="#ebfafa"

# Title color for boxes
theme[title]="#ebfafa"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#7081d0"

# Background color of selected item in processes box
theme[selected_bg]="#04d1f9"

# Foreground color of selected item in processes box
theme[selected_fg]="#ebfafa"

# Color of inactive/disabled text
theme[inactive_fg]="#323449"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#ebfafa"

# Background color of the percentage meters
theme[meter_bg]="#323449"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#37f499"

# Cpu box outline color
theme[cpu_box]="#37f499"

# Memory/disks box outline color
theme[mem_box]="#a48cf2"

# Net up/down box outline color
theme[net_box]="#f16c75"

# Processes box outline color
theme[proc_box]="#f265b5"

# Box divider line and small boxes line color
theme[div_line]="#323449"

# Temperature graph colors
theme[temp_start]="#37f499"
theme[temp_mid]="#04d1f9"
theme[temp_end]="#f265b5"

# CPU graph colors
theme[cpu_start]="#37f499"
theme[cpu_mid]="#f265b5"
theme[cpu_end]="#a48cf2"

# Mem/Disk free meter
theme[free_start]="#f265b5"
theme[free_mid]="#04d1f9"
theme[free_end]="#f265b5"

# Mem/Disk cached meter
theme[cached_start]="#04d1f9"
theme[cached_mid]="#f265b5"
theme[cached_end]="#04d1f9"

# Mem/Disk available meter
theme[available_start]="#f7c67f"
theme[available_mid]="#f1fc79"
theme[available_end]="#f7c67f"

# Mem/Disk used meter
theme[used_start]="#37f499"
theme[used_mid]="#a48cf2"
theme[used_end]="#37f499"

# Download graph colors
theme[download_start]="#37f499"
theme[download_mid]="#a48cf2"
theme[download_end]="#f265b5"

# Upload graph colors
theme[upload_start]="#a48cf2"
theme[upload_mid]="#04d1f9"
theme[upload_end]="#f265b5"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#a48cf2"
theme[process_mid]="#37f499"
theme[process_end]="#7081d0"
